"""users table

Revision ID: a3fa62213ba0
Revises: 
Create Date: 2018-04-20 14:49:23.093650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fa62213ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('link_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('colors', sa.String(length=255), nullable=True),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('sizes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('link_name')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_color'), 'product', ['color'], unique=False)
    op.create_index(op.f('ix_product_colors'), 'product', ['colors'], unique=False)
    op.create_index(op.f('ix_product_images'), 'product', ['images'], unique=False)
    op.create_index(op.f('ix_product_info'), 'product', ['info'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_joined'), 'user', ['joined'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_pre_tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_color'), 'cart', ['color'], unique=False)
    op.create_index(op.f('ix_cart_discount'), 'cart', ['discount'], unique=False)
    op.create_index(op.f('ix_cart_tax'), 'cart', ['tax'], unique=False)
    op.create_index(op.f('ix_cart_total'), 'cart', ['total'], unique=False)
    op.create_index(op.f('ix_cart_total_pre_tax'), 'cart', ['total_pre_tax'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=255), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['prod_name'], ['product.link_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_color'), 'purchase', ['color'], unique=False)
    op.create_index(op.f('ix_purchase_date'), 'purchase', ['date'], unique=False)
    op.create_index(op.f('ix_purchase_discount'), 'purchase', ['discount'], unique=False)
    op.create_index(op.f('ix_purchase_price'), 'purchase', ['price'], unique=False)
    op.create_index(op.f('ix_purchase_size'), 'purchase', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_size'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_price'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_discount'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_date'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_color'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_cart_total_pre_tax'), table_name='cart')
    op.drop_index(op.f('ix_cart_total'), table_name='cart')
    op.drop_index(op.f('ix_cart_tax'), table_name='cart')
    op.drop_index(op.f('ix_cart_discount'), table_name='cart')
    op.drop_index(op.f('ix_cart_color'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_joined'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_info'), table_name='product')
    op.drop_index(op.f('ix_product_images'), table_name='product')
    op.drop_index(op.f('ix_product_colors'), table_name='product')
    op.drop_index(op.f('ix_product_color'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
